#! /bin/sh

portdir=$(portageq portdir)

urls=$(./sun-fetch.py -q --mode id $1)

if [ "`arch`" == "i686" ] ; then
	archset="(i686|i586|i486)"
elif [ "`arch`" == "ia64" ] ; then
	archset="ia64"
fi

echo ${archset} 

for x in $urls ; do
	z=$(echo $x | grep "^http:" | egrep ${archset})
	if [ ! -z "$z" ] ; then
		filename=`echo $z | sed -r "s_.*/(.*)_\1_"`
		wget "${x}" -O ${portdir}/distfiles/$filename
	fi
done
