.TH FINDCLASS "1" "May 2005" "javatollkit 0.1.0" "User Commands"
.SH NAME
sun-fetch \- Fetches programs automatically from the Sun website
.SH SYNOPSIS
.B sun-fetch
\fI[options]\fB 
program-id
.SH DESCRIPTION
.PP
.I sun-fetch
Wades through the application forms, accepts the licenses and downloads
sensible files from the Sun website.
.SH OPTIONS 
.TP
\fB-v --verbose\fI
Generates a more verbose output.

.SH AUTHORS
Karl Trygve Kalleberg <karltk@gentoo.org>, 2004-2005


.SH "SEE ALSO"
java-config(1)

