.TH FINDCLASS "1" "May 2005" "javatollkit 0.1.0" "User Commands"
.SH NAME
findclass \- Searches for installed classes or packages
.SH SYNOPSIS
.B findclass
\fI[options]\fB 
class.or.package.Name
.SH DESCRIPTION
.PP
.I findclass
Searches the system for the given package or class name, and prints 
its location to stdout.
.SH OPTIONS 
.TP
\fB-v --verbose\fI
Generates a more verbose output.

.SH AUTHORS
Karl Trygve Kalleberg <karltk@gentoo.org>, 2004-2005
.br
Fabio Lessa <flessa@gmail.com>, 2005


.SH "SEE ALSO"
java-config(1)

